version: "3.8"

services:
  rabbitmq:
    container_name: rabbitmq
    image: rabbitmq:management-alpine
    networks:
      - abpmic-network
    ports:
      - "15672:15672"
      - "5672:5672"

  redis:
    container_name: redis
    image: redis:alpine
    networks:
      - abpmic-network
    ports:
      - "6379:6379"

  postgres:
    container_name: postgres
    image: postgres:latest
    volumes:
      - sqldata:/var/lib/postgresql/data
    networks:
      - abpmic-network
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USERS_USER: postgres
      POSTGRES_PASSWORD: postgres

  minio:
    image: minio/minio:latest
    container_name: minio
    networks:
      - abpmic-network
    ports:
      - "9000:9000"
      - "9001:9090"
    environment:
      MINIO_ROOT_USER: admin
      MINIO_ROOT_PASSWORD: admin1q2w3E*
    volumes:
      - ../minio:/data
    command: server /data --console-address ":9090"

volumes:
  esdata:
  sqldata:
networks:
  abpmic-network:
    external: true
